name: Node.js CI & Release

on:
  push:
    tags:
      - 'v*'  # 只有 push 形如 v1.0.0 的 tag 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v22.14.0]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Zip dist folder
        run: zip -r dist-${{ github.ref_name }}.zip dist

      - name: Generate SHA256 checksum
        run: sha256sum dist-${{ github.ref_name }}.zip > dist-${{ github.ref_name }}.zip.sha256

      - name: Upload artifact (zip + checksum)
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.ref_name }}
          path: |
            dist-${{ github.ref_name }}.zip
            dist-${{ github.ref_name }}.zip.sha256

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ github.ref_name }}

      - name: Create Tagged Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload zip and checksum to Tagged Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist-${{ github.ref_name }}.zip
            dist-${{ github.ref_name }}.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update Latest Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Latest Release
          files: |
            dist-${{ github.ref_name }}.zip
            dist-${{ github.ref_name }}.zip.sha256
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

